name = "personal-blog-api"
main = "src/index.ts"
compatibility_date = "2024-04-05"

[vars]
DISCORD_APPLICATION_ID = "1491052368626843668"

[[d1_databases]]
binding = "DB"
database_name = "personal-blog"
database_id = "0f871179-2302-42be-a614-8f96e1692766"

[[r2_buckets]]
binding = "ASSETS_BUCKET"
bucket_name = "personal-blog-assets"
